"""empty message

Revision ID: 45d8373efd72
Revises: 9100aef96c32
Create Date: 2016-08-04 23:20:14.177749

"""

# revision identifiers, used by Alembic.
revision = '45d8373efd72'
down_revision = '9100aef96c32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('role')
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], )
    )
    ### end Alembic commands ###
