"""empty message

Revision ID: 509d6a7d4e6c
Revises: 45d8373efd72
Create Date: 2016-08-05 22:03:05.044790

"""

# revision identifiers, used by Alembic.
revision = '509d6a7d4e6c'
down_revision = '45d8373efd72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=10000), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    ### end Alembic commands ###
