"""empty message

Revision ID: e8765e3f35e3
Revises: ff63d47e8208
Create Date: 2016-08-17 22:51:46.195179

"""

# revision identifiers, used by Alembic.
revision = 'e8765e3f35e3'
down_revision = 'ff63d47e8208'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_column('user', 'nickname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=1)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    ### end Alembic commands ###
